# development:
#   host: dev.example.com
#   handle: <your site handle from engine>
#   email: john@doe.net
#   api_key: <your api key here>
# staging:
#   host: staging.example.com
#   handle: <your site handle from engine>
#   email: john@doe.net
#   api_key: <your api key here>
# production:
#   host: www.example.com
#   handle: <your site handle from engine>
#   email: john@doe.net
#   api_key: <your api key here>
